#version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    #environment:
    #  POSTGRES_DB: ${POSTGRES_DB}
    #  POSTGRES_USER: ${POSTGRES_USER}
    #  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    #ports:
    #  - "5433:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./weather_viewer:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    container_name: django_app
    depends_on:
      - db


volumes:
  postgres_data: