version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    #ports:
    #  - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./weather_viewer:/app
    ports:
      - "8000:8000"
    container_name: django_app
    env_file:
      - .env
    depends_on:
      - db


volumes:
  postgres_data: