FROM python:3.12.2-alpine

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apk update && apk add --no-cache gcc musl-dev postgresql-dev
RUN python -m pip install --upgrade pip

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY /weather_viewer .

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]