services:
  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: django_app
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - static_volume:/user/static
    command: >
          sh -c "python manage.py collectstatic --noinput &&
                 chmod -R 755 /user/static &&
                 python manage.py migrate &&
                 gunicorn weather_viewer.wsgi:application --bind 0.0.0.0:8000"
  nginx:
    build:
      context: ./docker/nginx/
    container_name: weather_nginx
    volumes:
      - static_volume:/user/static
    depends_on:
      - web
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

volumes:
  static_volume:
  postgres_data: